steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
  '-t', 'gcr.io/$PROJECT_ID/arpit-dbt-tutorial/dbt-bigquery-template:latest',
  '.' ]
images:
- 'gcr.io/$PROJECT_ID/arpit-dbt-tutorial/dbt-bigquery-template:latest'
- 'gcr.io/$PROJECT_ID/arpit-dbt-tutorial/dbt-bigquery-template:$COMMIT_SHA'

