steps:
  - name: 'gcr-io/cloud-builders/docker'
    args: ['build', -'t', 'us-west2-docker.pkg.dev/arpit-dbt/arpit-dbt-tutorial/dbt-bigquery-template:latest','.']

images:
  - 'us-west2-docker.pkg.dev/arpit-dbt/arpit-dbt-tutorial/dbt-bigquery-template:tag1'
