steps:
  # Build test image.
    - name: "gcr.io/kaniko-project/executor:${_KANIKO_VERSION}"
      id: "build-ci"
      args:
        - "--dockerfile=Dockerfile"
        - "--destination=${_DBT_APP_IMAGE}"
        - "--cache=true"
        - "--cache-repo=${_DBT_APP_IMAGE}/cache"
        - "--use-new-run"

   # Check SQL Formatting
    - name: "${_DBT_APP_IMAGE}"
      id: "sql-fluff"
      waitFor: ["build-ci"]
      entrypoint: bin/bash'
      args: ["-c","echo","hello world"]
    #  args: ["sqlfluff","lint", "/opt/dbt-bigquery-template/models"]

  #  # DBT test.
  #   - name: "${_DBT_APP_IMAGE}"
  #     id: "dbt-debug"
  #     waitFor: ["build-ci"]
  #     entrypoint: bash
  #     args: ["dbt" "debug"]

substitutions:
  _DBT_APP_IMAGE: "us-west2-docker.pkg.dev/arpit-dbt/arpit-dbt-tutorial/dbt-bigquery-template:${COMMIT_SHA}" 
  _KANIKO_VERSION: "v1.8.0"

timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY