version: '3'

services:
  dbt-bigquery-template-dev:
    image: dbt-bigquery-template:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: poetry run ${DBT_COMMAND}
    volumes:
    - ./credentials/dbt-user.json:/opt/cronjob-etl/credentials/dbt-user.json:ro
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "128M"
    environment:
      - LOGLEVEL=DEBUG